### ISSUE TITLE
gnuplot error: can't find libpng16.so.16

### ISSUE THREAD

**Issue by dwightkuo** [peterjc/pico_galaxy#17]
I get the following error when I try to use mummer after installing on my local Galaxy (v16.07):

```
Fatal error: Exit code 1 ()
1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
# reading input file "out.ntref" of length 388490
# construct suffix tree for sequence of length 388490
# (maximum reference length is 536870908)
# (maximum query length is 4294967295)
# process 3884 characters per dot
#....................................................................................................
# CONSTRUCTIONTIME /opt/shed_tools/mummer/3.23/iuc/package_mummer_3_23/9ddc606546c3/mummer out.ntref 0.05
# reading input file "/remote/RMS/users/galaxyd/files/051/dataset_51390.dat" of length 298399
# matching query-file "/remote/RMS/users/galaxyd/files/051/dataset_51390.dat"
# against subject-file "out.ntref"
# COMPLETETIME /opt/shed_tools/mummer/3.23/iuc/package_mummer_3_23/9ddc606546c3/mummer out.ntref 0.15
# SPACE /opt/shed_tools/mummer/3.23/iuc/package_mummer_3_23/9ddc606546c3/mummer out.ntref 0.66
4: FINISHING DATAgnuplot: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory
WARNING: Using outdated gnuplot, use v4.0 for best results
WARNING: Turning of --size option for compatibility
Reading delta file out.delta
Writing plot files /tmp/118873.1.galaxy.q/tmpAmGeOm/ref_qry.fplot, /tmp/118873.1.galaxy.q/tmpAmGeOm/ref_qry.rplot
Writing gnuplot script /tmp/118873.1.galaxy.q/tmpAmGeOm/ref_qry.gp
Rendering plot /tmp/118873.1.galaxy.q/tmpAmGeOm/ref_qry.png
gnuplot: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory
WARNING: Unable to run 'gnuplot /tmp/118873.1.galaxy.q/tmpAmGeOm/ref_qry.gp', Inappropriate ioctl for device
Traceback (most recent call last):
  File "/opt/shed_tools/toolshed.g2.bx.psu.edu/repos/peterjc/mummer/5f5a358b281f/mummer/tools/mummer/mummer.py", line 68, in <module>
    shutil.move(png_image, png_out)
  File "/opt/rh/python27/root/usr/lib64/python2.7/shutil.py", line 301, in move
    copy2(src, real_dst)
  File "/opt/rh/python27/root/usr/lib64/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/opt/rh/python27/root/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/tmp/118873.1.galaxy.q/tmpAmGeOm/ref_qry.png'
```

**Comment by peterjc** [comment]
This looks like something has gone wrong with installing MUMMER and/or GNUPLOT - did you let the Tool Shed do this for you via the declared dependencies? i.e. https://github.com/peterjc/pico_galaxy/blob/master/tools/mummer/tool_dependencies.xml

This in turn depends on  https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_mummer_3_23/tool_dependencies.xml and https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_gnuplot_4_6/tool_dependencies.xml - If so, I'll push this issue to https://github.com/galaxyproject/tools-iuc/issues

Do you know if MUMMER will work on this system outside of Galaxy?

**Comment by dwightkuo** [comment]
Hi Peter,

Yes I exclusively used the Tool Shed to install MUMMER and its
dependencies. When I try doing the same commands using a system installed
MUMMER, this seems to work fine.

Thanks,

Dwight

**Comment by peterjc** [comment]
Thank you for the additional information. I've filed https://github.com/galaxyproject/tools-iuc/issues/1001 as I think there is something in the IUC package dependencies.

**Comment by peterjc** [comment]
With https://toolshed.g2.bx.psu.edu/view/peterjc/mummer/d9f3d4779507 I've updated the mummer wrapper to v0.0.7 which includes slightly clearer error messages - but does not solve this dependency problem.

Unfortunately the BioConda gnuplot 4.6.0 package also doesn't support PNG output yet: https://github.com/bioconda/bioconda-recipes/pull/4655

Are you using conda for your Galaxy? Perhaps I should give up on the legacy Tool Shed packages and point at the newer BioConda gnuplot 5.0.4 and their mummer & ghostscript which ought to work...
https://anaconda.org/bioconda/gnuplot
https://anaconda.org/bioconda/mummer
https://anaconda.org/bioconda/ghostscript
