### ISSUE TITLE
seq_filter_by_mapping 0.0.6 fails on Galaxy 20.09

### ISSUE THREAD

**Issue by ynanyam** [peterjc/pico_galaxy#36]
Fails with the following error

```
Traceback (most recent call last): 
File "/lustre/project/galaxy/galaxy-py3/galaxy-base/database/shed_tools/toolshed.g2.bx.psu.edu/repos/peterjc/seq_filter_by_mapping/481b0a925e66/seq_filter_by_mapping/tools/seq_filter_by_mapping/seq_filter_by_mapping.py", line 205, 
in <module> load_mapping_ids(filename, pair_mode, ids) 
File "/lustre/project/galaxy/galaxy-py3/galaxy-base/database/shed_tools/toolshed.g2.bx.psu.edu/repos/peterjc/seq_filter_by_mapping/481b0a925e66/seq_filter_by_mapping/tools/seq_filter_by_mapping/seq_filter_by_mapping.py", line 171, 
in load_mapping_ids qname, flag, rest = line.split("\t", 2) 
TypeError: a bytes-like object is required, not 'str'
```

I see that in the repo master branch and in test toolshed we have 0.0.7 available, can you make it available on the production toolshed? 

Thanks,
Yash

**Comment by peterjc** [comment]
Done, sorry about this oversight - v0.0.7 was specifically addressing this Python 2/3 change. Thanks for reporting this.
